# Generated by Django 5.0.6 on 2024-06-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagetotexthistory",
            name="image_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imagetotexthistory",
            name="llm_model",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="imagetotexthistory",
            name="model_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
